version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: investment-tracker-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/investmentTracker"

  mongo:
    image: mongo
    volumes:
      - /Users/johntsai/Documents/Projects/investment-tracker/mongodb_data:/data/db
    ports:
      - "27017:27017"
